// puzzles.js — 24 chess puzzles with difficulty and theme fields
// Board coordinates: row 0 = rank 8 (black's back rank), row 7 = rank 1 (white's back rank)
// col 0 = a-file, col 7 = h-file
// Piece codes: w=white, b=black; p=pawn, n=knight, b=bishop, r=rook, q=queen, k=king

const PUZZLES = [
  // ─────────────────────────────────────────────
  // OPENING — intermediate (1), beginner (1)
  // ─────────────────────────────────────────────
  {
    id: "italian-initiative",
    title: "意大利开局的先手主动权",
    difficulty: "intermediate",
    theme: "opening",
    description: "白方先走。王都已安置好，适合从轻子活跃度和中央张力继续推演。",
    board: [
      ["br", null, "bb", "bq", null, "br", "bk", null],
      ["bp", "bp", null, null, "bb", "bp", "bp", "bp"],
      [null, null, "bn", "bp", null, "bn", null, null],
      [null, null, "bp", null, "wp", null, null, null],
      [null, null, "wb", null, null, null, null, null],
      [null, null, "wn", null, null, "wn", null, null],
      ["wp", "wp", "wp", null, "wq", "wp", "wp", "wp"],
      ["wr", null, null, null, "wr", null, "wk", null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 2,
    fullmove: 11,
  },
  {
    id: "kings-pawn-opening",
    title: "王兵开局基础站位",
    difficulty: "beginner",
    theme: "opening",
    description: "白方先走。双方各走了几步棋，白方已占据中心，现在思考如何最优开展轻子。",
    board: [
      ["br", "bn", "bb", "bq", "bk", "bb", null, "br"],
      ["bp", "bp", "bp", "bp", null, "bp", "bp", "bp"],
      [null, null, null, null, null, "bn", null, null],
      [null, null, null, null, "bp", null, null, null],
      [null, null, null, null, "wp", null, null, null],
      [null, null, null, null, null, "wn", null, null],
      ["wp", "wp", "wp", "wp", null, "wp", "wp", "wp"],
      ["wr", "wn", "wb", "wq", "wk", "wb", null, "wr"],
    ],
    turn: "w",
    castling: { w: { kingSide: true, queenSide: true }, b: { kingSide: true, queenSide: true } },
    enPassant: null,
    halfmove: 2,
    fullmove: 3,
  },

  // ─────────────────────────────────────────────
  // MIDDLEGAME — intermediate (3), beginner (2), expert (2)
  // ─────────────────────────────────────────────
  {
    id: "minor-piece-squeeze",
    title: "双马与象的空间压制",
    difficulty: "intermediate",
    theme: "middlegame",
    description: "黑方先走。双方子力完整度较高，适合练习如何在拥挤局面中找出突破点。",
    board: [
      ["br", null, null, "bq", null, "br", "bk", null],
      ["bp", "bp", null, "bb", null, "bp", "bp", "bp"],
      [null, null, "bp", "bp", "bn", "bn", null, null],
      [null, null, null, null, "bp", null, null, null],
      [null, null, "wp", "wp", "wp", null, null, null],
      [null, null, "wn", "wb", null, "wn", null, null],
      ["wp", "wp", null, null, "wq", "wp", "wp", "wp"],
      ["wr", null, null, null, "wr", null, "wk", null],
    ],
    turn: "b",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 18,
  },
  {
    id: "bishop-pair-advantage",
    title: "双象的中局优势",
    difficulty: "intermediate",
    theme: "middlegame",
    description: "白方先走。白方拥有双象优势，黑方双马被动，适合练习利用双象开放斜线进攻。",
    board: [
      [null, null, null, "bq", null, "br", "bk", null],
      ["bp", "bp", "bn", null, null, "bp", "bp", "bp"],
      [null, null, "bn", "bp", null, null, null, null],
      [null, null, null, null, "bp", null, null, null],
      [null, null, "wb", null, "wp", null, null, null],
      [null, null, null, "wb", null, "wn", null, null],
      ["wp", "wp", "wp", null, null, "wp", "wp", "wp"],
      ["wr", null, null, "wq", null, "wr", "wk", null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 1,
    fullmove: 14,
  },
  {
    id: "open-file-pressure",
    title: "开放列的压制",
    difficulty: "intermediate",
    theme: "middlegame",
    description: "白方先走。d列已开放，白方车占据主动位置，练习如何利用开放列渗透黑阵。",
    board: [
      [null, null, null, "bq", null, "br", "bk", null],
      ["bp", "bp", null, null, "bb", "bp", "bp", "bp"],
      [null, null, "bn", null, "bp", "bn", null, null],
      [null, null, null, "bp", null, null, null, null],
      [null, null, "wp", null, "wp", null, null, null],
      [null, null, "wn", null, null, "wn", null, null],
      ["wp", "wp", null, "wr", null, "wp", "wp", "wp"],
      ["wr", null, "wb", "wq", null, null, "wk", null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 16,
  },
  {
    id: "central-control-beginner",
    title: "中心控制入门",
    difficulty: "beginner",
    theme: "middlegame",
    description: "白方先走。局面开放，白方在中心拥有优势，练习如何激活后翼车并扩大优势。",
    board: [
      ["br", null, "bb", "bq", null, "br", "bk", null],
      ["bp", "bp", "bp", null, null, "bp", "bp", "bp"],
      [null, null, "bn", null, "bp", "bn", null, null],
      [null, null, null, "bp", null, null, null, null],
      [null, null, "wb", null, "wp", null, null, null],
      [null, null, "wn", null, null, "wn", null, null],
      ["wp", "wp", "wp", "wp", null, "wp", "wp", "wp"],
      ["wr", null, null, "wq", null, "wr", "wk", null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: true }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 9,
  },
  {
    id: "queenside-attack-beginner",
    title: "后翼进攻基础",
    difficulty: "beginner",
    theme: "middlegame",
    description: "黑方先走。黑方在后翼积累了兵力优势，练习如何发动后翼进攻扩大优势。",
    board: [
      [null, "br", null, null, null, "br", "bk", null],
      [null, null, "bq", null, "bb", "bp", "bp", "bp"],
      ["bp", null, "bp", null, "bp", "bn", null, null],
      [null, "bp", null, null, null, null, null, null],
      [null, "wp", null, null, null, null, null, null],
      ["wp", null, "wp", null, "wp", "wn", null, null],
      [null, null, "wq", null, "wb", "wp", "wp", "wp"],
      [null, "wr", null, null, null, "wr", "wk", null],
    ],
    turn: "b",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 2,
    fullmove: 22,
  },
  {
    id: "king-attack-expert",
    title: "王翼猛攻",
    difficulty: "expert",
    theme: "middlegame",
    description: "白方先走。白方集中大量兵力准备王翼强攻，黑王防守脆弱，需要精确计算将杀路线。",
    board: [
      [null, null, null, "bq", "br", null, "bk", null],
      ["bp", "bp", null, null, null, null, "bp", "bp"],
      [null, null, "bb", null, null, "bn", null, null],
      [null, null, null, "bp", "bp", null, null, null],
      [null, null, null, "wp", "wp", "wn", "wb", null],
      [null, null, "wn", null, null, null, "wp", null],
      ["wp", "wp", null, null, "wq", null, null, "wp"],
      ["wr", null, null, null, "wr", null, "wk", null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 21,
  },
  {
    id: "positional-squeeze-expert",
    title: "位置型绞杀",
    difficulty: "expert",
    theme: "middlegame",
    description: "白方先走。白方占有明显的位置优势，黑方子力拥堵，需要找到突破黑阵的精确计划。",
    board: [
      [null, null, null, "bq", null, "br", "bk", null],
      ["bp", null, "bb", null, null, "bp", "bp", "bp"],
      [null, "bp", null, "bp", "bn", "bn", null, null],
      [null, null, null, null, "bp", null, null, null],
      [null, null, "wp", "wp", "wp", "wb", null, null],
      [null, "wn", null, "wb", null, "wn", null, null],
      ["wp", "wp", null, null, "wq", "wp", "wp", "wp"],
      ["wr", null, null, "wr", null, null, "wk", null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 1,
    fullmove: 26,
  },

  // ─────────────────────────────────────────────
  // TACTIC — intermediate (3), beginner (2), expert (2)
  // ─────────────────────────────────────────────
  {
    id: "fork-tactic-beginner",
    title: "马的双重攻击",
    difficulty: "beginner",
    theme: "tactic",
    description: "白方先走。白方有机会利用马的双重攻击同时威胁黑王和黑后，找到这步棋！",
    board: [
      [null, null, null, null, "bk", null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, "bq", null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, "wn", null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, "wk", null, null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 28,
  },
  {
    id: "pin-tactic-beginner",
    title: "绝对钉住",
    difficulty: "beginner",
    theme: "tactic",
    description: "白方先走。白方可以用象绝对钉住黑马，使其无法移动，从而获得子力优势。",
    board: [
      [null, null, null, null, "bk", null, null, null],
      [null, null, null, null, "bn", null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, "wb", null, null, null, null, null],
      [null, null, null, null, "wk", null, null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 1,
    fullmove: 19,
  },
  {
    id: "skewer-tactic-intermediate",
    title: "串打战术",
    difficulty: "intermediate",
    theme: "tactic",
    description: "白方先走。白方可以用车沿开放列实施串打，迫使黑后移动后吃掉后面的车。",
    board: [
      [null, null, null, null, "bk", null, null, null],
      [null, null, null, "bq", null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, "br"],
      ["wr", null, null, null, "wk", null, null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 31,
  },
  {
    id: "discovered-attack-intermediate",
    title: "闪击战术",
    difficulty: "intermediate",
    theme: "tactic",
    description: "白方先走。移动白方马可以揭开象的斜线，同时马本身也攻击黑方子力，双重威胁！",
    board: [
      [null, null, null, "bk", null, null, null, null],
      [null, null, "bq", null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, "bp", null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, "wn", null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, "wk", null, "wb", null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 24,
  },
  {
    id: "back-rank-mate-intermediate",
    title: "底线将杀",
    difficulty: "intermediate",
    theme: "tactic",
    description: "白方先走。黑王被困在底线，己方兵挡住了逃路，白方车可以一击制胜！",
    board: [
      [null, null, null, null, null, "br", "bk", null],
      ["bp", "bp", null, null, null, "bp", "bp", "bp"],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      ["wp", "wp", null, null, null, "wp", "wp", "wp"],
      [null, null, null, null, "wr", null, "wk", null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 27,
  },
  {
    id: "double-check-expert",
    title: "双将绝杀",
    difficulty: "expert",
    theme: "tactic",
    description: "白方先走。白方可以施展双将，黑王无论如何移动都逃不过将杀，计算最精确的路线！",
    board: [
      ["bk", null, null, null, null, null, null, null],
      [null, "bp", null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, "wn", null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      ["wr", null, null, null, "wk", null, null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 2,
    fullmove: 33,
  },
  {
    id: "queen-sacrifice-expert",
    title: "后的牺牲换杀",
    difficulty: "expert",
    theme: "tactic",
    description: "白方先走。通过精妙的后牺牲，白方可以强制将杀，需要深度计算对方的所有应招。",
    board: [
      [null, null, null, null, null, "br", "bk", null],
      ["bp", "bp", null, null, null, "bp", null, "bp"],
      [null, null, null, null, null, null, "bp", null],
      [null, null, null, "bb", null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, "wn", null, null, null, "wp", null],
      ["wp", "wp", null, null, "wq", "wp", null, "wp"],
      [null, null, null, null, null, "wr", "wk", null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 1,
    fullmove: 29,
  },

  // ─────────────────────────────────────────────
  // ENDGAME — beginner (3), intermediate (3), expert (2)
  // ─────────────────────────────────────────────
  {
    id: "passed-pawn-race",
    title: "通路兵竞速",
    difficulty: "beginner",
    theme: "endgame",
    description: "白方先走。残局兵形非常直接，适合练习计算谁先升变以及何时该用王拦截。",
    board: [
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, "bk", null],
      [null, null, null, null, null, "bp", null, null],
      [null, null, null, null, "bp", null, null, null],
      [null, null, null, "wp", null, null, null, null],
      [null, null, null, null, null, null, "wk", null],
      [null, null, null, null, null, null, null, "wp"],
      [null, null, null, null, null, null, null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 51,
  },
  {
    id: "king-pawn-endgame-beginner",
    title: "王兵残局升变",
    difficulty: "beginner",
    theme: "endgame",
    description: "白方先走。白方通路兵已接近底线，关键是王的支援路线，练习基础王兵残局升变技巧。",
    board: [
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, "bk", null, null, null, null],
      [null, null, null, null, "wp", null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, "wk", null, null, null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 0,
    fullmove: 44,
  },
  {
    id: "rook-vs-pawn-beginner",
    title: "车对通路兵",
    difficulty: "beginner",
    theme: "endgame",
    description: "白方先走。白方用车阻止黑方通路兵升变，练习车对兵残局中车的正确拦截位置。",
    board: [
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, "bk", null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      ["bp", null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      ["wr", null, null, null, "wk", null, null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 1,
    fullmove: 48,
  },
  {
    id: "queen-endgame-race",
    title: "后残局抢先手",
    difficulty: "intermediate",
    theme: "endgame",
    description: "白方先走。双方都保留一枚后和若干兵，适合练习将军、兑后与通路兵竞速。",
    board: [
      [null, null, null, null, null, null, "bk", null],
      [null, null, null, null, null, "bp", null, "bp"],
      [null, null, null, null, "bp", null, "bp", null],
      [null, null, null, "bp", null, null, null, null],
      [null, null, "wp", null, "wp", null, null, null],
      [null, null, null, null, null, "wp", "wp", null],
      [null, null, null, "wq", null, null, null, "wp"],
      [null, null, null, null, null, null, "wk", null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 1,
    fullmove: 35,
  },
  {
    id: "rook-endgame-active-king",
    title: "车残局中的王的激活",
    difficulty: "intermediate",
    theme: "endgame",
    description: "黑方先走。双方各有一车，关键在于王的站位和兵形弱点的利用。",
    board: [
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, "br", null, "bk", null],
      [null, null, null, "bp", null, "bp", null, "bp"],
      [null, null, null, null, "bp", null, "bp", null],
      [null, null, null, "wp", null, null, null, null],
      [null, null, null, null, "wk", "wp", null, "wp"],
      [null, null, null, null, "wr", null, null, null],
      [null, null, null, null, null, null, null, null],
    ],
    turn: "b",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 4,
    fullmove: 42,
  },
  {
    id: "rook-endgame-seventh-rank",
    title: "车占第七横线",
    difficulty: "intermediate",
    theme: "endgame",
    description: "白方先走。白方车进入第七横线将对黑方造成极大压力，练习如何利用这一优势推进胜利。",
    board: [
      [null, null, null, null, null, null, "bk", null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, "bp", null, "bp", null],
      [null, null, null, null, null, "bp", null, null],
      [null, null, null, null, "wp", null, null, null],
      [null, null, null, null, null, "wp", null, null],
      [null, null, null, null, null, null, "wk", null],
      [null, null, null, null, "wr", null, null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 2,
    fullmove: 38,
  },
  {
    id: "opposite-colored-bishops",
    title: "异色象残局",
    difficulty: "expert",
    theme: "endgame",
    description: "黑方先走。异色象让和棋资源很多，但也容易漏看兵翼的切入点。",
    board: [
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, "bk", null, null],
      [null, null, null, "bp", null, null, null, null],
      [null, null, null, null, "bb", null, "bp", null],
      [null, null, "wb", null, null, null, null, null],
      [null, null, null, "wp", null, "wk", null, null],
      [null, null, null, null, null, null, "wp", null],
      [null, null, null, null, null, null, null, null],
    ],
    turn: "b",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 7,
    fullmove: 46,
  },
  {
    id: "rook-vs-bishop-expert",
    title: "车对象的残局技巧",
    difficulty: "expert",
    theme: "endgame",
    description: "白方先走。车对象残局理论上白方占优，但需要精确技术迫使黑方认输，避免错入和局。",
    board: [
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, "bk", null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, "bb", null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null],
      [null, null, null, "wk", null, "wr", null, null],
    ],
    turn: "w",
    castling: { w: { kingSide: false, queenSide: false }, b: { kingSide: false, queenSide: false } },
    enPassant: null,
    halfmove: 3,
    fullmove: 55,
  },
];
